#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(feat|fix|bump|chore|refactor|reformat|optimise|document|merge): .*"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood> <what was done>"
  echo "Allowed verbs in imperative mood: feat, fix, bump, chore, refactor, reformat, optimise, document, merge"
  echo "Example: feat: add login button"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  exit 1
fi
